---
title: "Homework 2 R Problem"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 4, fig.width = 6)
```


```{r}

set.seed(2)

```

### a) ACF

```{r}

# a) AR(1) series with phi = 0.5 
y.50 <-  arima.sim(model = list(ar = 0.5), n = 100)

# plot ACF of AR(1) series with phi = 0.5 
acf(y.50)

y_acf_values <- acf(y.50, plot = FALSE)

y_acf_values$acf

```

Comparing the ACF of phi = 0.5 with answer from Exercise 3.1, both have similar values.

### PACF 

```{r}

# plot PACF of AR(1) series with phi = 0.5 
acf(y.50, type = "partial")

y_pacf_values <- acf(y.50, plot = FALSE, type = "partial")

y_pacf_values$acf

```

The PACF with k > 2 are equal to 0 from Exercise 3.1. Here, it's slightly more or less than 0 when k > 2, which is still relatively similar to answer from Exercise 3.1.


### b) ACF

```{r}

# a) AR(1) series with phi = 0.98 
y.98 <-  arima.sim(model = list(ar = -0.98), n = 100)

# plot ACF of AR(1) series with phi = 0.98 
acf(y.98)

y_acf_values <- acf(y.98, plot = FALSE)

y_acf_values$acf

```

The ACF for phi = 0.98 in R, the values are also similar to Exercise 3.1.

### PACF 

```{r}

# plot PACF of AR(1) series with phi = 0.98 
acf(y.98, type = "partial")

y_pacf_values <- acf(y.98, plot = FALSE, type = "partial")

y_pacf_values$acf

```

The values in R here are also the same as PACF in Exercise 3.1b



